package com.ruanyun.web.model.general;
// Generated 2018-3-8 11:07:52 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TOrgInfo generated by hbm2java
 */
@Entity
@Table(name = "t_org_info"
)
public class TOrgInfo implements java.io.Serializable {


    private Integer orgInfoId;
    private String orgInfoNum;
    private String orgName;
    private String orgCode;
    private String code;
    private String parentCode;
    private String linkTel;
    private String userNum;
    private String createUserNum;
    private Date createTime;
    private Integer orgType;
    private String flag1;
    private String flag2;
    private String flag3;
    private BigDecimal stockRatio;
    private Integer stockRatioType;


    private String loginName;
    private String loginPass;

    private String parentName;

    public TOrgInfo() {
    }

    public TOrgInfo(String orgInfoNum, String orgName, String orgCode, String code, String parentCode, String linkTel, String userNum, String createUserNum, Date createTime, Integer orgType, String flag1, String flag2, String flag3, BigDecimal stockRatio, Integer stockRatioType) {
        this.orgInfoNum = orgInfoNum;
        this.orgName = orgName;
        this.orgCode = orgCode;
        this.code = code;
        this.parentCode = parentCode;
        this.linkTel = linkTel;
        this.userNum = userNum;
        this.createUserNum = createUserNum;
        this.createTime = createTime;
        this.orgType = orgType;
        this.flag1 = flag1;
        this.flag2 = flag2;
        this.flag3 = flag3;
        this.stockRatio = stockRatio;
        this.stockRatioType = stockRatioType;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "org_info_id", unique = true, nullable = false)
    public Integer getOrgInfoId() {
        return this.orgInfoId;
    }

    public void setOrgInfoId(Integer orgInfoId) {
        this.orgInfoId = orgInfoId;
    }

    @Column(name = "org_info_num", length = 100)
    public String getOrgInfoNum() {
        return this.orgInfoNum;
    }

    public void setOrgInfoNum(String orgInfoNum) {
        this.orgInfoNum = orgInfoNum;
    }

    @Column(name = "org_name", length = 100)
    public String getOrgName() {
        return this.orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    @Column(name = "org_code", length = 100)
    public String getOrgCode() {
        return this.orgCode;
    }

    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    @Column(name = "code", length = 100)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "parent_code", length = 100)
    public String getParentCode() {
        return this.parentCode;
    }

    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

    @Column(name = "link_tel", length = 100)
    public String getLinkTel() {
        return this.linkTel;
    }

    public void setLinkTel(String linkTel) {
        this.linkTel = linkTel;
    }

    @Column(name = "user_num", length = 100)
    public String getUserNum() {
        return this.userNum;
    }

    public void setUserNum(String userNum) {
        this.userNum = userNum;
    }

    @Column(name = "create_user_num", length = 100)
    public String getCreateUserNum() {
        return this.createUserNum;
    }

    public void setCreateUserNum(String createUserNum) {
        this.createUserNum = createUserNum;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name = "org_type")
    public Integer getOrgType() {
        return this.orgType;
    }

    public void setOrgType(Integer orgType) {
        this.orgType = orgType;
    }


    @Column(name = "flag1", length = 100)
    public String getFlag1() {
        return this.flag1;
    }

    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }

    @Column(name = "flag2", length = 100)
    public String getFlag2() {
        return this.flag2;
    }

    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    @Column(name = "flag3", length = 100)
    public String getFlag3() {
        return this.flag3;
    }

    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }

    @Column(name = "stock_ratio", precision = 10, scale = 4)
    public BigDecimal getStockRatio() {
        return this.stockRatio;
    }

    public void setStockRatio(BigDecimal stockRatio) {
        this.stockRatio = stockRatio;
    }

    @Column(name = "stock_ratio_type")
    public Integer getStockRatioType() {
        return this.stockRatioType;
    }

    public void setStockRatioType(Integer stockRatioType) {
        this.stockRatioType = stockRatioType;
    }

    @Transient
    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }


    @Transient
    public String getLoginPass() {
        return loginPass;
    }

    public void setLoginPass(String loginPass) {
        this.loginPass = loginPass;
    }


    @Transient
    public String getParentName() {
        return parentName;
    }

    public void setParentName(String parentName) {
        this.parentName = parentName;
    }
}


