package com.ruanyun.web.model.general;
// Generated 2018-3-10 14:34:04 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TStockRatio generated by hbm2java
 */
@Entity
@Table(name = "t_stock_ratio"
)
public class TStockRatio implements java.io.Serializable {


    private int id;
    private String stockRatioNum;
    private BigDecimal money;
    private String cycle;
    private BigDecimal priceRatio;
    private String symbol;
    private String flag1;
    private String flag2;
    private String flag3;

    public TStockRatio() {
    }


    public TStockRatio(int id) {
        this.id = id;
    }

    public TStockRatio(int id, String stockRatioNum, BigDecimal money, String cycle, BigDecimal priceRatio, String symbol, String flag1, String flag2, String flag3) {
        this.id = id;
        this.stockRatioNum = stockRatioNum;
        this.money = money;
        this.cycle = cycle;
        this.priceRatio = priceRatio;
        this.symbol = symbol;
        this.flag1 = flag1;
        this.flag2 = flag2;
        this.flag3 = flag3;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "stock_ratio_num", length = 100)
    public String getStockRatioNum() {
        return this.stockRatioNum;
    }

    public void setStockRatioNum(String stockRatioNum) {
        this.stockRatioNum = stockRatioNum;
    }

    @Column(name = "money", precision = 18)
    public BigDecimal getMoney() {
        return this.money;
    }

    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    @Column(name = "cycle", length = 100)
    public String getCycle() {
        return this.cycle;
    }

    public void setCycle(String cycle) {
        this.cycle = cycle;
    }

    @Column(name = "price_ratio", precision = 18, scale = 4)
    public BigDecimal getPriceRatio() {
        return this.priceRatio;
    }

    public void setPriceRatio(BigDecimal priceRatio) {
        this.priceRatio = priceRatio;
    }

    @Column(name = "symbol", length = 100)
    public String getSymbol() {
        return this.symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    @Column(name = "flag1", length = 100)
    public String getFlag1() {
        return this.flag1;
    }

    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }

    @Column(name = "flag2", length = 100)
    public String getFlag2() {
        return this.flag2;
    }

    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    @Column(name = "flag3", length = 100)
    public String getFlag3() {
        return this.flag3;
    }

    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }


}


